### ISSUE TITLE
Examples do not all execute correctly

### ISSUE THREAD

**Issue by rvodden** [rvodden/pysketcher#1]
from @rafaellehmkuhl

I'm trying to run the examples after installing through Pypi, but I cannot make them run.

The hello_world.py gives me ```NameError: name 'Text' is not defined```.
The beam1.py gives me ```NameError: name 'drawing_tool' is not defined```.

---

Table of progress:

|example|status|
|------|------|
|beam1.py|:ok_hand: fixed|
|beam2.py|:ok_hand: fixed|
|colors_test.py|:ok_hand: fixed|
|comprehensive_rectangles.py|:ok_hand: fixed|
|finite_differences.py|:ok_hand: fixed|
|flow_over_gaussian.py|:ok_hand: fixed|
|hatch_test.py|:ok_hand: fixed|
|hello_world.py|:ok_hand: fixed|
|integral_comic_strip.py|:running: need to be able to pass kwargs to backend|
|layered_medium_2.py|:ok_hand: fixed|
|layered_medium_3xi.py|:ok_hand: fixed|
|layered_medium_general.py|:ok_hand: fixed|
|mesh_function.py|:ok_hand: fixed|
|oscillator_sketch1.py|:ok_hand: fixed|
|~~oscillator_sketch2.py~~|:~~adds nothing above osclilator_sketch1.py~~|
|pendulum1.py|:persevere: fixed (with a bug - why is the mass not blue in the free body diagram?!?)|
|pendulum2.py|:ok_hand: fixed|
|simple_arc.py|:ok_hand: fixed|
|simple_arrow.py|:ok_hand: fixed|
|simple_axis.py|:ok_hand: fixed|
|simple_circle.py|:ok_hand: fixed|
|simple_curve.py|:ok_hand: fixed|
|simple_rectangle.py|:ok_hand: fixed|
|simple_spline.py|:ok_hand: fixed|
|simple_text.py|:ok_hand: fixed|
|simple_triangle.py|:ok_hand: fixed|
|simple_wall.py|:ok_hand: fixed|
|staggered_mesh_function.py|:ok_hand: fixed|
|vehicle.py|:ok_hand: fixed|
|vehicle_dim.py|:ok_hand: fixed|
|wheel_on_inclined_plane.py|:ok_hand: fixed|

**Comment by rvodden** [comment]
This is all working now aside from the comic strip stuff and the weird lack of blue ball on the end of the pendulum. I really don't think drawing comic strips is a priority for 0.1.0 so unless anyone shouts on this issue, I'll resolve the pendulum example and then call this done.

**Comment by ReblochonMasque** [comment]
I checked all examples in the repo. Except the 'comic-strip' ones (2 files), all are working: they produce an image, or a movie without throwing exceptions; that is not to say they are correct, I have not checked that.

The list is as follows:

**working examples**
```
animation.py     --> produces an .mp4
beam1.py
beam2.py
colors_test.py
comprehensive_rectangles.py
finite_differences.py
flow_over_gaussian.py
hatch_test.py
hello_world.py
layered_medium_2.py
layered_medium_3xi.py
layered_medium_general.py
mesh_function.py
oscillator_sketch1.py
pendulum1.py
pendulum2.py     --> produces an .mp4
simple_axis.py
staggered_mesh_function.py
vehicle.py
vehicle_dim.py
wheel_on_inclined_plane.py
```
**broken examples**
```
integral_comic_strip.py
ForwardEuler_comic_strip.py
```

I have submitted a PR to isolate the broken examples under a legacy folder

As a side question, not directly related to pysketcher: the images produced by matplorlib are huge (way larger than my 27 in screen) - there is a `tight_layout` option for `pyplot` that solves this with retina displays; does someone know what is the equivalent command for `matplotlib.Figure`?
