### ISSUE TITLE
Test image not provided

### ISSUE THREAD

**Issue by ReblochonMasque** [rvodden/pysketcher#322]
```
tests/utils/compare_image.py:27 ([doctest] tests.utils.compare_image.compare_images)
050         - *tol*: The comparison tolerance.
051 
052     Raises:
053         ValueError: If either of the provided images is not suitable.
054         IOError: If either of the image files cannot be found.
055 
056     Examples:
057         >>> img1 = "docs/images/wheel_on_inclined_plane.png"
058         >>> img2 = "docs/images/wheel_on_inclined_plane.png"
059         >>> compare_images(img1, img2, 0.001)
UNEXPECTED EXCEPTION: ValueError('Output image docs/images/wheel_on_inclined_plane.png does not exist.')
```

Visual inspection of the image produced indicates that there are probably no issues in the code under test and that the absence of the reference image is the reason for the failure.
However, a `ValueError` was raised, in lieu of an `IOError: If either of the image files cannot be found.`.

All 43 other tests pass.

**Comment by rvodden** [comment]
Which command are you using to run this? Are you running it as part of the nox build?

**Comment by rvodden** [comment]
The [image is provided here](https://github.com/rvodden/pysketcher/blob/master/docs/images/wheel_on_inclined_plane.png). I'm not able to replicate this. Can I close it? Or can you provide the commands you use to run this so I'm more able to help?

**Comment by ReblochonMasque** [comment]
I ran the tests with the IDE default test runner launch command (clicked on the menu).
IDK how to extract the command line generated, but I saved the `runConfiguration` file generated `pytest_in_tests.xml` - maybe you can use it? let me know if I need to dig deeper:

`<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="pytest in tests" type="tests" factoryName="py.test" nameIsGenerated="true">
    <module name="pysketcher-1" />
    <option name="INTERPRETER_OPTIONS" value="" />
    <option name="PARENT_ENVS" value="true" />
    <option name="SDK_HOME" value="" />
    <option name="WORKING_DIRECTORY" value="$PROJECT_DIR$/tests" />
    <option name="IS_MODULE_SDK" value="true" />
    <option name="ADD_CONTENT_ROOTS" value="true" />
    <option name="ADD_SOURCE_ROOTS" value="true" />
    <option name="_new_keywords" value="&quot;&quot;" />
    <option name="_new_parameters" value="&quot;&quot;" />
    <option name="_new_additionalArguments" value="&quot;&quot;" />
    <option name="_new_target" value="&quot;$PROJECT_DIR$/tests&quot;" />
    <option name="_new_targetType" value="&quot;PATH&quot;" />
    <method v="2" />
  </configuration>
</component>`


in addition to the current issue, I tried to run `$ pytest` from the `tests` directory - it ran 3 tests, and hung forever. Here is the output until the KB interrupt:

`$ pytest
======================================================================================== test session starts =========================================================================================
platform darwin -- Python 3.9.7, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /Users/ReblochonMasque/Projects/Projects/pysketcher-1/pysketcher-1, configfile: pyproject.toml
plugins: hypothesis-6.24.1
collected 44 items                                                                                                                                                                                   

test_angle.py ...^C
`
