### ISSUE TITLE
need a requirements.txt file

### ISSUE THREAD

**Issue by ReblochonMasque** [rvodden/pysketcher#323]
There are a few unexpected dependencies that are not documented; a `requirements.txt` file would address this issue.

It could be something like this:

```
celluloid
hypothesis
matplotlib
numpy
PIL
scipy

```

Would you like me to submit a PR?

**Comment by rvodden** [comment]
The project uses a pyproject.yaml rather than requirements.txt. You should be able to build it using [poetry](https://python-poetry.org/). Build instructions would be helpful thoug, so I'll put some together.

**Comment by ReblochonMasque** [comment]
Noted - I've never used poetry; I cloned the repo directly from my fork.
Yes build instructions would be useful.

**Comment by rvodden** [comment]
In the mean time you should be able to do something like this:

<switch to the virtual environment manager of your choice>
`pip install poetry nox`
`nox`

And that will run all the linting and tests against python 3.7 and 3.8 (I need to update the build chain to include 3.9 and 3.10 when its released)
