### ISSUE TITLE
There are no contributor guidelines

### ISSUE THREAD

**Issue by ReblochonMasque** [rvodden/pysketcher#334]
There are no contributor guidelines.

Could contributor guidelines be added, please?

**Comment by ReblochonMasque** [comment]
bump!

**Comment by ReblochonMasque** [comment]
All right then - I guess that if you don't welcome contributors, this is not necessary!
Closing the issue!

**Comment by rvodden** [comment]
Appologies @ReblochonMasque  I was having some personal issues at home. As you're well aware from our previous conversations I'm very interested in contributions. It's a real shame you chose to take that approach. I've re-opened the issue as I will write some contribution documentation.

**Comment by rvodden** [comment]
WIP here: https://github.com/rvodden/pysketcher/blob/fix/%23334/CONTRIBUTING.rst

**Comment by rvodden** [comment]
@ReblochonMasque can you have a read of ☝️ . It would be really helpful to have a 2nd pair of eyes before I merge it in

**Comment by ReblochonMasque** [comment]
Sorry to hear you've had some personal issues. 
The document in question is perfect!
