### ISSUE TITLE
figure.show()

### ISSUE THREAD

**Issue by hdeavila1992** [rvodden/pysketcher#756]
The examples code works fine, but don't hold the figure generate. It only shows then, for a fraction of a second.

import pysketcher as ps
from pysketcher.backend.matplotlib import MatplotlibBackend

figure = ps.Figure(0.0, 5.0, 0.0, 5.0, MatplotlibBackend)

a = ps.Point(1.0, 3.0)
b = ps.Point(4.0, 3.0)

line = ps.Line(a, b)
figure.add(line)
figure.show()

print("Dont hold")

**Comment by rvodden** [comment]
Thanks Hernando. Can you tell me a little bit more about the environment you're running this in? Are you running from an xterm window, from an IDE, which operating system are you running on?
